language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=veoliaeau)
  - secure: OYtaTrzxcKP/pXObtjZcYxBxvoOPU69BoSpmIrYoYs7nkpgef9opePqa3knL+GysBScKxWff9cNaXRnVZs8w+286g3fHattsPjIaGrNRvKxH9ajJxRxqA1ZL8RDy6Dk43rqY9pvTaC690ivfFnIIRxWw/r5CcfrRRdpLq38L9Gy4UlOlyZLqAYjXOBF7YQLfBULx9jtRgqUg1/UViqw0Cx1avjRJD5tVfufjJhqrXv5DEgoc0q+yCyVgu2lTjY8lvuGIvdRD4xfD58yaoTutuvJyhajIql3qE+vfkQOCi39Vl5H6o81BykTwd1FUIwombvVpH2KXl8gL73Nq04pAmSR/v6+NR4z4KVrpdK2xEe/gpOs95ojkUpRlTf1z0Jab28guJ6v2ftbTfAye4GSpDbEdKAB2UabIDggYQVHch4q7bqom57ePI5leiQAOZFggGzNiUnFhV2mUaVa1cbHRnmgAILAFWWyqkFlvxh4z5PiIhx3A1IMKIkLYkgpwbeoq9PpOPpFDekiVddrij20u59HqD915ZUfcll/9diPl3PSHtIsT3fEaHhcyYhH7hgUpT1qbCv7VLCx4KOxEAXJ0aVUhKrTgFmiK+vKWRe29caKlYbOOV/JjgueB+0UQVJTyJyMm7jOhhoEHEiicmZYukNJF4JlptpSdojB87uwtRtA=
  # MATTERMOST_HOOK_URL
  - secure: bZQnmCY6WpCV7GDuPLwK84xuIneSYL/7NGD7z7ZTeasyCc8WKdATL/Pt21gFi9PG0T3gpZdG7HgykTjhgzO7oar4f8CgIZANNH/NXTi46slHm+gO2NuAzcXEQOg36m2a+nliywwnV0p7G7a0Z5fn+i1mtiGjmYbOdfEw1ymJ9T5YGZU68I0p4i6tSHkDQ/x9lPw1sMngYMZ52BSsfybdfpbB5RWYWJvc5yp1rMpm0/U38PIT6AKy2AosB/PJzQ2teiHg6vmqYobhjcQ+2vi5q/M1LdwdxR6aqAbmHde2sto5jq2g7mitSqpt4yfWF4gBaaL2JS1aJ6UydUwT4EdnZPODaMDebtR/M6su2Y6ijTYh5GA6DnmeseCrtM8GmNWxgyXaMotEOp20+YY7xRHLuNoe3RQhKQ4CjTjYFZlhL3PfQCbuR1CzWDjDEzVzfLNeqtkvvZDnBi7Qb4Zm80/a395dx9EUqhq3WGm8QFVpIjaE7DKyeVlPLu96BWC76IOiranC53YJMpoimSt4Vu+WzCIykn74lhub9ffdcRZ+2FapCM6xWCWdKyiG2YGgagxx9GoW2cCYFEDq3e+iaB9uN6fU5us6QLB89wYyjWNG6y2uAK8XNM1Y1QOpEKQ+4ioxNGTABM4rgEC3CTmu8Y7KwIG5G07Ck+MMA5LA1vJQgMk=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
  - /^renovate.*?/
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
