language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/veoliaeau.git"
  - secure: D7OYKybpxwkJ7SINQ0h4v0KY+kgO0BTWASR0uT2h2rbMdc4QfovPfy8QBtXEIuvilhnmagTezzWNwHh5rJ3aNOrFEw09PtI/7LfVKtdLyAkxBKX83PBUeOZI0phb1Pj8jvfd4NRDNZ/GqorjujxYTruuhytmUxCMLOJCr2y0bJxRcxtzpDjxmDjLYDClapWhd4KcGH6ord9hw6hOpx2f4JZQMlBNc+2kcyJ/C64Olmq48fOVkbSPraeKqQL2Dx2OeXxoTzpfLPjJKTTaDsm4Is7SM/n6xyM8y2Xxdl/vliK5gIuZBrxUg0mDkz9bEL4S4XbbXd9EUNB9Rjm4+Tf9TuySj/Y9jKHoMgADZt/520V4AStXLWKX0LAMkIWLQdk2GU/Zcs6TnwR/BaSJP420Ua8DiuewWi5azcO1o1om1Bq5egpVE5Qz6wBhme3pP03BtmVa2dpwwgeOygQ43qpMn6G5ZaYCPuHyCPFNRp82uKZnzg2ls5R1WwongmqAtJ61yUyjqxaDWvxHYnwJu9cyFYwq2Ko2CaRjLSR9zTVTzoQdT6Hp9iJThUvRXlUpWONvS8mjlz7WUxgWOwARVNKg+ihtzaYkJup0jTOPrKQdwuIOwUD+EWLfxirh8TpLZ/2Uqzn7ychOyIJYPBDtQTF358VtwRMKqJa2cb5ENrKWb5s=
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=latest yarn deploy
  on:
    branch: prod
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_429b7ab1b4ac_key -iv $encrypted_429b7ab1b4ac_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
